### ISSUE TITLE
Integrate amenities using OpenStreetMap as a data source

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/website#361]
- Grocery stores (shop=supermarket)
- Hospitals
- Parks

To begin with. It could go near the TOD status. 

Use [HOT Export Tool](https://export.hotosm.org/en/v3/exports/1cb8c987-b08e-403a-9c6a-4bdf989fce6a) to get the data until Metro Extracts comes back online. 

Right now HOT E.T. cannot get large areas – see the map screenshot – which is why I want Metro Extracts. 
<img width="421" alt="screenshot 2018-02-04 22 44 38" src="https://user-images.githubusercontent.com/1330459/35788760-015365d2-09fd-11e8-926b-a5bc77c38289.png">

We can update this data once every couple of months. 

"How do you help developers find a place to build a high density place that has a grocery store, and a liquor store, and a bus line that takes you to an L station?"

**Comment by stevevance** [comment]
YAML config:
````
planet_osm_point:
  types:
    - points
  select:
    - access
    - 'addr:housenumber'
    - 'addr:street'
    - amenity
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - 'medical_system:western'
    - name
    - opening_hours
    - operator
    - 'operator:type'
    - shop
    - status
  where:
    - building IS NOT NULL
    - amenity='marketplace' OR shop='convenience' OR shop='supermarket'
    - 'amenity IN (''restaurant'',''fast_food'',''cafe'',''bar'',''pub'')'
    - amenity='doctors'
    - amenity='hospital'
    - amenity='library'
planet_osm_polygon:
  types:
    - polygons
  select:
    - access
    - 'addr:housenumber'
    - 'addr:street'
    - amenity
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - leisure
    - 'medical_system:western'
    - name
    - opening_hours
    - operator
    - 'operator:type'
    - shop
    - status
  where:
    - building IS NOT NULL
    - amenity='marketplace' OR shop='convenience' OR shop='supermarket'
    - 'amenity IN (''restaurant'',''fast_food'',''cafe'',''bar'',''pub'')'
    - amenity='doctors'
    - amenity='hospital'
    - leisure='park'
    - amenity='library'
````

**Comment by stevevance** [comment]
Consider adding community gardens...although there isn't a good tag for it. 
`leisure=garden` has 21 features in and around Humboldt Park, but the companion tag `garden:type=community` that further specifies the type of garden has only six features.

It looks like the vast majority of them should have the community tag on them, as only a couple of them are decorative/botanical gardens.

**Comment by stevevance** [comment]
Libraries don't seem to be showing up in the testing. Perhaps I added the tag in the YAML above after I already downloaded a Planet extract from HOT.

**Comment by stevevance** [comment]
There's an issue in that thousands of amenities are not mapped on the South and West Sides of Chicago. 
<img width="488" alt="map_of_osm_amenities_in_chicago" src="https://user-images.githubusercontent.com/1330459/38946624-a4be080e-42ff-11e8-83ee-22347c786804.png">

**Comment by stevevance** [comment]
I'm talking to MAPS Corps about obtaining their data.

**Comment by stevevance** [comment]
This feature can be portrayed as a [10 minute neighborhood](https://halifax.retales.ca/2018/08/10-minute-neighbourhoods/) analyzer.

**Comment by stevevance** [comment]
This is the current export configuration:

````
planet_osm_point:
  types:
    - points
  select:
    - access
    - 'addr:housenumber'
    - 'addr:street'
    - 'addr:city'
    - 'addr:state'
    - 'addr:postcode'
    - amenity
    - building
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - name
    - opening_hours
    - operator
    - 'operator:type'
    - shop
    - status
    - website
  where:
    - leisure = 'sports_centre'
    - amenity='marketplace' OR shop='convenience' OR shop='supermarket'
    - 'amenity IN (''restaurant'',''fast_food'',''cafe'',''bar'',''pub'')'
    - amenity='doctors'
    - amenity='hospital'
    - amenity='library'
    - amenity='bank'
    - office='ngo'
    - amenity='community_centre'
    - amenity='clinic'
    - healthcare='clinic'
planet_osm_polygon:
  types:
    - polygons
  select:
    - access
    - 'addr:housenumber'
    - 'addr:street'
    - 'addr:city'
    - 'addr:state'
    - 'addr:postcode'
    - building
    - amenity
    - 'health_facility:bed'
    - 'health_facility:level'
    - 'health_facility:type'
    - leisure
    - name
    - opening_hours
    - operator
    - 'operator:type'
    - shop
    - status
    - website
  where:
    - leisure = 'sports_centre'
    - amenity='marketplace' OR shop='convenience' OR shop='supermarket'
    - 'amenity IN (''restaurant'',''fast_food'',''cafe'',''bar'',''pub'')'
    - amenity='doctors'
    - amenity='hospital'
    - leisure='park'
    - amenity='library'
    - amenity='bank'
    - office='ngo'
    - amenity='community_centre'
    - amenity='clinic'
    - healthcare='clinic'
````
